version: '3'

volumes:
  lms_ead_local_postgres_data: {}
  lms_ead_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: lms_ead_local_django
    container_name: lms_ead_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      - network-app

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: lms_ead_production_postgres
    container_name: lms_ead_local_postgres
    volumes:
      - lms_ead_local_postgres_data:/var/lib/postgresql/data
      - lms_ead_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - network-app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2023"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - network-app

  # docs:
  #  image: lms_ead_local_docs
  #  container_name: lms_ead_local_docs
  #  build:
  #    context: .
  #    dockerfile: ./compose/local/docs/Dockerfile
  #  env_file:
  #    - ./.envs/.local/.django
  #  volumes:
  #    - ./docs:/docs:z
  #    - ./config:/app/config:z
  #    - ./lms_ead:/app/lms_ead:z
  #  ports:
  #    - '9000:9000'
  #  command: /start-docs

networks: 
  network-app:
    driver: bridge