# Generated by Django 4.1.9 on 2023-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="Name of Course")),
                (
                    "course_description",
                    models.CharField(blank=True, max_length=555, verbose_name="Description of Course"),
                ),
            ],
        ),
    ]
