# Generated by Django 4.1.9 on 2023-05-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_rename_course_description_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="default.png", upload_to="uploads/courses/% Y/% m/% d/"),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(default="N", max_length=1),
        ),
    ]
